name: cpi-pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:2.x.x-lite
    env:
      HOST_TMN: 61d37b08trial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
      HOST_OAUTH: 61d37b08trial.authentication.ap21.hana.ondemand.com
      OAUTH_CLIENTID: ${{ secrets.DEV_CLIENT_ID }}
      OAUTH_CLIENTSECRET: ${{ secrets.DEV_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      # Set environment variable for source directory of IFlow
      - run: |
          echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/sync/flashpipe_demo_iflow" >> $GITHUB_ENV
      # Upload/Update design time
      - name: 'Update/Upload demo upload'
        run: /usr/bin/update_designtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: flashpipedemoiflow
          IFLOW_NAME: "flashpipe demo iflow"
          PACKAGE_ID: FlashpipeDemoPackage
          PACKAGE_NAME: "Flashpipe Demo Package"
      # Deploy runtime
      - name: 'Deploy iflow to runtime'
        run: /usr/bin/deploy_runtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: flashpipedemoiflow
